### ISSUE TITLE
PINN training question

### ISSUE THREAD

**Issue by fsfing** [demroz/pinn-ms#1]
Hello, I have read your code and met some problems. Could you help me to answer?  @demroz 

Q1: First, test data is generated in the generateTrainingData folder, and then training is conducted in trainUnet.py. Why does the plot show no change?
![image](https://github.com/demroz/pinn-ms/assets/57214227/67b34203-c20e-45e4-a087-e01257808dae)

Q2: What is the reason that testDataLoss you wrote seems not to be used when the loss function is computed?

I would appreciate it if you could answer my questions.

**Comment by demroz** [comment]
The issue is most likely angler. Modify
EPSILON_0 = 8.85418782e-12

MU_0 = 1.25663706e-6
to

EPSILON_0 = 1.0
MU_0 = 1.0

in angler/constants.py

That should fix your problem

**Comment by fsfing** [comment]
thanks you for your reply.
I am runned data-free(trainUnet.py) without using these two parameters. The Enn after visualization is null. What might be the cause of this problem?

In addition, I have a question. I used generate-fdfd-dataset.py to generate fdfd-data after modifying the two parameters(EPSILON_0 = 1.0   and MU_0 = 1.0), but I found it  stopped , but it was already 60G big. This is ok?

**Comment by fsfing** [comment]
/thanks you for your reply.  @demroz 
I ran no data (trainUnet.py) and was not using these two parameters. However, the Enn after visualization is null. What might be the cause of this problem?
Below is my revised code based on yours.
`
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import numpy as np
from torch.autograd import grad
import matplotlib.pyplot as plt 
from angler import Simulation
import pandas as pd
from UNetArch import *
from plotUtil import *

from pathlib import Path
FILE = Path(__file__).resolve()
ROOT = FILE.parents[0]

datafile = '/home/sffu/workspaces/PINN/generateTrainingData/fdfd-data/fdfd-data.dat'
data = pd.read_pickle(datafile)         # (10, 20)
test_data = data[0:100] # only test 100 samples from full dataset

Nx = test_data['Ezre'][0].shape[0] # field shape  96
Ny = test_data['Ezre'][0].shape[1] #              192


cct = torch.tensor(data['cc'][0].todense(), dtype=torch.complex64).cuda()
Np = 16
p = 0.443
h = 0.6
dx = p/Np
wave = 0.633
omega = 2*np.pi/wave
J = 1j*omega*torch.tensor(data['J'][0].reshape(1, Nx*Ny)).cuda() # copy current source  i*omega

nnre = UNet(1)
nnim = UNet(1)
nnre.cuda()
nnim.cuda()

savedir = "nnTrainingData/"
slicesdir = savedir+"slices/"
fielddir = savedir+"fields/"
pdfdir = savedir+"pdf/"


def nnLoss(E, F, eps):
    '''
    Neural network loss function

    Parameters
    ----------
    E : torch tensor
        real part of NN predicted E field
    F : torch tensor
        imag part --//--
    eps : torch tensor
        discretized epsilon field

    Returns
    -------
    tensor
        ||\nabla^2 E + omega^2 epsilon E - J||^2

    '''
    eps = eps.reshape(-1, Nx*Ny)
    field = E+1j*F
    temp = omega**2*eps.T*field.T
    l1 = cct @ field.T + temp - J.T             # Eq.4
    print("loss:", torch.mean(torch.abs(l1)))
    return torch.mean(torch.abs(l1))

def testDataLoss(E, F, Etar_re, Etar_im, eps):
    '''
    producted loss statistics on test data
    
    Parameters
    ----------
    E : nn predicted real field
    F : nn predicted imagninary field
    
    Etar_re : target real field
    Etar_im : target imagninary field
    eps : epsilon field

    Returns
    -------
    None.
    '''
    nnfield = E + 1j*F
    target_field = Etar_re + 1j * Etar_im
    eps = eps.reshape(-1, Nx*Ny)
    
    l1 = cct @ nnfield.T + omega**2 * eps.T * nnfield.T - J.T             
    l2 = torch.sum(torch.abs(nnfield - target_field))
    
    print("pinn loss", l1.item(), "l1 loss", l2.item())
    
def getTestBatch(numeps, epoch):
    '''
    Parameters
    ----------
    numeps : int
        number of epsilon fields
    epoch : int
        epoch #

    Returns
    -------
    eps : tensor
        test epsilon field
    Etar_re : tensor
        real part of Ez
    Etar_im : tensor
        complex part of Ez

    '''
    inds = np.arange(epoch*numeps, (epoch+1)*numeps)
    eps = np.zeros((numeps, 1, Nx, Ny))
    Etar_re = np.zeros((numeps, Nx, Ny))
    Etar_im = np.zeros((numeps, Nx, Ny))
    for i in range(0, numeps):
        eps[i, 0, :, :] = test_data['eps'][inds[i]]
        Etar_re[i, :, :] = test_data['Ezre'][inds[i]]
        Etar_im[i, :, :]  = test_data['Ezim'][inds[i]]
        
    eps = torch.tensor(eps, dtype=torch.float32)
    return eps, Etar_re, Etar_im


def generateEps(r):
    '''
    Parameters
    ----------
    r : tensor
        list of radii

    Returns
    -------
    eps : tensor
        epsilon field

    '''
    x = np.linspace(-p*12/2, p*12/2, Np*12)
    y = np.linspace(-p*3, p*3, Np*6)
    xx, yy = np.meshgrid(x, y)
    radlocs = np.arange(-5, 6)*p
    eps = np.ones(xx.shape)
    for i in range(0, len(radlocs)):
        eps[(np.abs(xx-radlocs[i]) < r[i]) &
            (np.abs(yy) < h/2)
            ] = 2**2
    return eps

def generateTrainBatch(numeps):
    '''
    Parameters
    ----------
    numeps : number of epsilons

    Returns
    -------

    eps : tensor
        eps field

    '''
    with torch.no_grad():
        eps = np.zeros((numeps, 1, Nx, Ny))
        for i in range(numeps):
            rads = np.random.uniform(size=11)*p/2
            # print("rads: ", rads)
            eps[i, 0, :, :] = generateEps(rads)
            
        eps = torch.tensor(eps, dtype=torch.float32)
    return eps

nepochs = 50000
params = list(nnre.parameters()) + list(nnim.parameters())
pp = 1e-4 # optimizer training rate
optimizer = torch.optim.Adam(params, lr=pp, weight_decay=1e-5)

train_loss_ar = [] # training loss
test_loss_ar = [] # testing loss
test_norm_error_ar = []
epochNo = [] # for testing

for epoch in range(nepochs):
    batch_eps = generateTrainBatch(10)
    batch_eps = batch_eps.cuda()
    
    optimizer.zero_grad()
    loss = nnLoss(nnre(batch_eps), nnim(batch_eps), batch_eps)
    loss.backward()
    optimizer.step()
    train_loss_ar.append(loss.item()) # loss data
    
    print(epoch)
    if epoch % 1000 == 0:
        epochNo.append(epoch)
        nnre.cpu()
        nnim.cpu()
        
        trainBatchSize = 10
        nBatches = int(len(test_data)/trainBatchSize)   # len(test_data)=10 --> nBatches=1
        print("current nBatches: ", nBatches)
        q = 0

        test_batch_loss = []
        test_batch_norm_error = []

        for testEpoch in range(nBatches):
            epst, Etest, Ftest = getTestBatch(trainBatchSize, testEpoch)
            Enn = nnre(epst).reshape(trainBatchSize, Nx, Ny)
            Fnn = nnim(epst).reshape(trainBatchSize, Nx, Ny)
            
            testLoss = nnLoss(nnre(epst).cuda(), nnim(epst).cuda(), epst.cuda())
            test_batch_loss.append(testLoss.item())
            
            nnfield = Enn + 1j*Fnn
            tfield = Etest + 1j*Ftest
            
            norm_error = np.sum(np.abs(nnfield.detach().numpy() - tfield)**2)/np.sum(np.abs(tfield)**2)    
            test_batch_norm_error.append(norm_error)
            
            for j in range(trainBatchSize):
                plotFullFields(nnfield[j,:,:], tfield[j,:,:], epoch, q, fielddir)
                q += 1

        test_loss_ar.append(np.mean(test_batch_loss))
        test_norm_error_ar.append(np.mean(test_batch_norm_error))

        plt.figure()
        plt.plot(np.log(train_loss_ar))
        plt.plot(epochNo, np.log(test_loss_ar))
        plt.legend(['train loss', 'test loss'])
        plt.show()
        plt.savefig("./nnTrainingData/train-test.png")
        
        plt.figure()
        plt.plot(test_norm_error_ar)
        plt.legend(['F norm error'])
        plt.show()
        plt.savefig("./nnTrainingData/F_norm_error.png")

        nnre.cuda()
        nnim.cuda()
        

np.savetxt(savedir+'train_loss', train_loss_ar)
np.savetxt(savedir+'test_loss', test_loss_ar)
np.savetxt(savedir+'fro_loss', test_norm_error_ar)

model_name_re = 'nnre2'
model_name_im = 'nnim2'
save_path_re = os.path.join(str(ROOT)+"/nnTrainingData/trainedNets/", "{}.pt".format(model_name_re))
save_path_im = os.path.join(str(ROOT)+"/nnTrainingData/trainedNets/", "{}.pt".format(model_name_im))

torch.save(nnre.state_dict(), save_path_re)
torch.save(nnim.state_dict(), save_path_im)

`
In addition, I have a question. I used generate-fdfd-dataset.py to generate fdfd-data after modifying the two parameters(EPSILON_0 = 1.0 and MU_0 = 1.0), but I found it stopped , but it was already 60G big. This is ok?

**Comment by demroz** [comment]
what does the loss look like?
what does the training data look like?

check what the matrix cct looks like as well.

**Comment by fsfing** [comment]
@demroz 
nnloss：
![image](https://github.com/demroz/pinn-ms/assets/57214227/5f54128c-d083-4564-b05f-3f0655a3c7d1)

training data：
Isn't trainUnet.py training data generated randomly?

In trainUnet.py, the dataset generated by generate-fdfd-dataset.py should only be used for testing, right?


cct matrix is (18432， 18432).
![image](https://github.com/demroz/pinn-ms/assets/57214227/c351dc1a-b403-4beb-a5f8-9ce611f4c095)
it's so big.

**Comment by demroz** [comment]
convert cct to a spart scipy matrix and use plt.spy and make sure you
adjust the size of the markers so that you can see the structure of the
matrix, also give me the values of the actual diagonal

**Comment by fsfing** [comment]
![image](https://github.com/demroz/pinn-ms/assets/57214227/91634883-caca-48b4-bc8f-8d13b3891200)
I draw a subgraph with  the size of 20*20, according to the method you mentioned. It's ok ?  @demroz 

![image](https://github.com/demroz/pinn-ms/assets/57214227/e3cacd58-9abf-405d-a477-6ae0f6027eb9)
This is the overall cct for abs, and you can see that there are some red dots on the diagonal. @demroz

**Comment by fsfing** [comment]
I made statistics on the data generation time of gengerate-fdfd-dataset.py. I found that it would take 70~100s for per round of generation, which take too long for the datasize=10000, which made me confused. Can you answer it? @demroz 

![image](https://github.com/demroz/pinn-ms/assets/57214227/75873510-0ef7-465f-b24c-8d00c484f366)

**Comment by demroz** [comment]
I dont know. Are you running this on a laptop? This code is written for a
workstation

**Comment by fsfing** [comment]
I ran it on a server. How long did it take you? @demroz 
Is there something wrong with the data I generated up here?

**Comment by demroz** [comment]
it takes 1-2 seconds per field for me. Theres something wrong with the way
you're generating the field, and i'm not sure what it is. What do the
fields look like

**Comment by fsfing** [comment]
"What do the fields look like"    
I don't quite understand what you said. Can you help me find out what is wrong with my code?  @demroz 
`# -*- coding: utf-8 -*-
"""
Created on Mon Apr  4 10:21:25 2022
@author: noise
"""
import os
import numpy as np
from angler import Simulation
import pandas as pd
import time

def generateEps(rads, index, xx, yy, radlocs, h):
    eps = np.ones(xx.shape)
    for i in range(0, len(radlocs)):
        eps[(np.abs(xx-radlocs[i]) < rads[i]) &
            (np.abs(yy) < h/2)
            ] = index**2
    return eps

def generateDataset(parameterDictionary):

    datasize = parameterDictionary['datasize']
    numRadii = parameterDictionary['numRadii']
    index = parameterDictionary['index']
    wave = parameterDictionary['wave']
    dx = parameterDictionary['dx']
    p = parameterDictionary['p']
    h = parameterDictionary['h']
    NPML = parameterDictionary['NPML']
    pol = parameterDictionary['pol']
    BC = parameterDictionary['BC']
    datadir = parameterDictionary['datadir']
    filename = parameterDictionary['filename']
    omega = 2*np.pi/wave
    
    dict = []
    if not os.path.isdir(datadir):
        os.makedirs(datadir)

    for i in range(datasize):
        d = []
        print("-----{}".format(i))
        start_time = time.time()
        rads = np.random.uniform(size=numRadii)*p/2     # [0, p/2) 即0 到 0.2215 之间
        
        Np = int(p/dx)
        x = np.linspace(-p*(len(rads)+1)/2, p*(len(rads)+1)/2, Np*(len(rads)+1))
        y = np.linspace(-p*3, p*3, Np*6)
        xx, yy = np.meshgrid(x, y)
        
        radlocs = np.arange(-np.floor(len(rads)/2), np.ceil(len(rads)/2))*p
        eps = generateEps(rads, index, xx, yy, radlocs, h)
        
        sim = Simulation(omega, eps, dx, NPML, pol)
        sim.src[NPML[0]+15, :] = 20
        sim.solve_fields()
        
        Ex_re = np.real(sim.fields['Ex'])
        Ex_im = np.imag(sim.fields['Ex'])
        
        Ey_re = np.real(sim.fields['Ey'])
        Ey_im = np.imag(sim.fields['Ey'])
        
        Ez_re = np.real(sim.fields['Ez'])
        Ez_im = np.imag(sim.fields['Ez'])
        
        Hx_re = np.real(sim.fields['Hx'])
        Hx_im = np.imag(sim.fields['Hx'])
        
        Hy_re = np.real(sim.fields['Hy'])
        Hy_im = np.imag(sim.fields['Hy'])
        
        Hz_re = np.real(sim.fields['Hz'])
        Hz_im = np.imag(sim.fields['Hz'])
        
        J = sim.src
        Dyb = sim.derivs['Dyb']
        Dyf = sim.derivs['Dyf']
        Dxb = sim.derivs['Dxb']
        Dxf = sim.derivs['Dxf']
        
        cc = Dxf.dot(Dxb)+Dyf.dot(Dyb)
        d = {
          'radii' : rads,
          'eps' : eps,
          'Exre' : Ex_re,
          'Exim' : Ex_im,
          'Eyre' : Ey_re,
          'Eyim' : Ey_im,
          'Ezre' : Ez_re,
          'Ezim' : Ez_im,
          'Hxre' : Hx_re,
          'Hxim' : Hx_im,
          'Hyre' : Hy_re,
          'Hyim' : Hy_im,
          'Hzre' : Hz_re,
          'Hzim' : Hz_im,
          'J' : J,
          'cc' : cc,
          'dxe': Dxb,
          'dxh': Dxf,
          'dye': Dyb,
          'dyh': Dyf
          }
        dict.append(d)
        end_time = time.time()
        time_ = end_time-start_time
        print("time: {}s".format(time_))
        
    df = pd.DataFrame.from_dict(dict)     
    df.to_pickle(datadir+filename)



parameterDictionary = {'datasize': 10000,
                       'numRadii': 11,
                       'index': 2,
                       'wave': 0.633,
                       'dx': 0.443/16,
                       'p': 0.443,
                       'h': 0.6,
                       'NPML': [10, 0],
                       'pol': 'Ez',
                       'BC' : False,
                       'datadir': '/home/sffu/workspaces/PINN/generateTrainingData/fdfd-data/',
                       'filename': 'fdfd-data.dat'}

print(generateDataset(parameterDictionary))
`

I just removed the comment.

**Comment by fsfing** [comment]
Friend, may I ask which country are you from? What chat software do you like to use on the Internet? 
I hope I can communicate with you more conveniently.

**Comment by fsfing** [comment]
Hey, I commented some code in generate-fdfd-dataset.py because it wasn't used in the training code. Then, it was discovered that the data generation became much faster.
![image](https://github.com/demroz/pinn-ms/assets/57214227/59f59e96-203d-426b-aca0-ec761a7f76bc)


![image](https://github.com/demroz/pinn-ms/assets/57214227/13be0488-c478-4628-8785-e58df0123ca5)

I have visualized cct（np.abs）, but I am not sure if the number of cct is correct, I may need your help to look at it. @demroz

**Comment by demroz** [comment]
you didn't visualize the way I asked you to. Please use plt.spy

**Comment by fsfing** [comment]
Fig.1
![image](https://github.com/demroz/pinn-ms/assets/57214227/be97acff-9c73-49b3-b794-45cd16b0445b)
In Fig. 1, the above figure is the visualization of sparse matrix, and the following figure is the visualization of diagonal absolute value of sparse matrix. Please help me to see if the drawing is correct. @demroz

**Comment by demroz** [comment]
ok, what do the fields look like?

**Comment by fsfing** [comment]
This is the field where I train visualization. @demroz 
Compared with (a) in Figure 2, I think this is far from ideal.
![image](https://github.com/demroz/pinn-ms/assets/57214227/72ec49fd-9c7d-4b07-8517-1e4369bcf339)


I'm curious about your fig. 2(a) is very interesting, so I would like to recreate it. But I don't know how to do it, can you share your implementation fig. The code of 2(a)? Or in your GitHub code, can you give a detailed guide?

I sincerely hope you can help me and look forward to your reply.
![image](https://github.com/demroz/pinn-ms/assets/57214227/7db9ff41-be43-4d60-b0a7-3f15ce9a0ebf)

**Comment by demroz** [comment]
your figure 1 tells meyou didnt actually modify angler in the way I asked
you to. Please do that

**Comment by fsfing** [comment]
![image](https://github.com/demroz/pinn-ms/assets/57214227/a356c9f2-4ea1-491d-818e-4cc15d0eac6f)
I modified it here. Is it correct? @demroz 

![image](https://github.com/demroz/pinn-ms/assets/57214227/1388fafa-48b8-4e25-b648-bad6b3dd72d4)
I passed the jupyter test, and they all did get 1.0.

This is the printed value in the solve_fields function in simulation.
![image](https://github.com/demroz/pinn-ms/assets/57214227/4002f08f-efda-437b-bbc2-9fb6b6a02216)

**Comment by fsfing** [comment]
May I ask whether your Fig.2 (a) is realized through the two files of generate-fdfd-dataset.py and trainUnet.py?

**Comment by demroz** [comment]
Change DEFAULT_LENGTH_SCALE to 1.0

Fig 1. a. was made in matlab. You'll need to basically generate some data
with FDFD and the neural network approach and then plot the real parts of
the field.

**Comment by fsfing** [comment]
Ok, I'll try again. This is the modified visualization. @demroz 
![image](https://github.com/demroz/pinn-ms/assets/57214227/19478308-9080-4000-b2b5-cb9d9aba5676)

Can I see your matlab code (about implementing your Fig.2 (a))? 
I hope to implement your paper Fig.2 (a) through python visualization.

**Comment by fsfing** [comment]
I think I see what you mean. Using trianUnet. After py training, use continue-trainUnet. py to verify?
This is where I adopted continue-trainUnet. py visualizes the result. @demroz 

![image](https://github.com/demroz/pinn-ms/assets/57214227/f50207f7-2dad-43d5-975b-d8eadf4c320e)

**Comment by fyl-nju** [comment]
@fsfing Hey,I have met the same question. I modified angler but the figures during training are blank, how you visualize the result using continue-trainUnet?
